### ISSUE TITLE
Dataset release date

### ISSUE THREAD

**Issue by shawrby** [TJRadarLab/TJ4DRadSet#1]
Hi,

First of all, thank you for your wonderful research!

When will the dataset be released?

**Comment by silent-zhou** [comment]
+1

**Comment by vehicle-jyw** [comment]
+1

**Comment by TJRadarLab** [comment]
Thank you for your attention to our work！ At present, we are confirming the data sensitivity with relevant departments. This issue will not be closed until the access link is displayed on the current page.

**Comment by Hyeokreal** [comment]
Looking foward to the release date too!

It would be great, if you could share some sample (small) data in advance.

**Comment by Do-woon** [comment]
+1

**Comment by solanian** [comment]
+1

**Comment by yjlee-icsl** [comment]
+1

**Comment by shawrby** [comment]
@TJRadarLab 

I'm still looking forward to it.  
If possible, could you please release a mini sample dataset?

**Comment by hyeon-mun** [comment]
+1

**Comment by TJRadarLab** [comment]
> @TJRadarLab
> 
> I'm still looking forward to it. If possible, could you please release a mini sample dataset?

Thank you for your attention. We released some samples and provided a simple visualization script.
![snapshot](https://user-images.githubusercontent.com/46335822/198658369-816f5ec5-0ed0-4286-aceb-432a4b0861ab.png)

**Comment by TJRadarLab** [comment]
> Thank you for your attention. We released some samples and provided a simple visualization script

We released some samples and provided a simple visualization script.

**Comment by shawrby** [comment]
@TJRadarLab 

Thank you so much!
Could you release camera and lidar data to understand the scene?

**Comment by shawrby** [comment]
@TJRadarLab 

Thank you so much!
Could you release camera image data to understand the scene?

I hope what I have requested is possible.

**Comment by TJRadarLab** [comment]
> @TJRadarLab
> 
> Thank you so much! Could you release camera image data to understand the scene?
> 
> I hope what I have requested is possible.

The images involve privacy and desensitization issues, which cannot be opened at present. Thank you for your understanding and support.

**Comment by shawrby** [comment]
@TJRadarLab 

Approximately when will the full dataset be released?
