### ISSUE TITLE
Camera data release

### ISSUE THREAD

**Issue by santimontiel** [TJRadarLab/TJ4DRadSet#17]
Hello everyone!

Firstly, thank you so much for your work! I am an incoming PhD student at the University of Alcalá, Madrid, Spain. My research group and I are interested in working on camera + 4D-radar fusion for perception.

Could you please update the current situation on the camera data release? Will it be possible to access it soon?

Thank you so much for your collaboration.

Santi

**Comment by TJRadarLab** [comment]
We have released the relevant data for the approved applications.
