### ISSUE TITLE
Regarding the Dataset availibility 

### ISSUE THREAD

**Issue by Manishnayak234** [TJRadarLab/TJ4DRadSet#19]
Hi I am Manish, a masters student from IIT Patna. I am doing my research in this Radar and camera fusion. Can you share the dataset with me. It will be helpful.

**Comment by Sawyer-Wu** [comment]
您好，你的邮件我已经收到，我会尽快给您回复，谢谢。

**Comment by Manishnayak234** [comment]
感谢您的回复
