### ISSUE TITLE
Radar rawdata structure

### ISSUE THREAD

**Issue by shawrby** [TJRadarLab/TJ4DRadSet#2]
Thanks for the mini dataset you released.

I have a question.

**1)** Looking at the radar raw data, it has 8 values as shown in the picture below.
![image](https://user-images.githubusercontent.com/54407464/198694527-d6c2bd36-a4b0-402c-8829-732a7689f750.png)
What does each mean?

**2)** How many frames of radar raw data have you accumulated?

**Comment by TJRadarLab** [comment]
1）It means [x,y,z,Vr,range,power,alpha,beta], and we only used the dimensions of [0,1,2,3,5].
2) The 4D radar frames are accumulated in provided SDK, the number of frames is not specified in the technical document. Maybe I'll ask technical support later.

**Comment by shawrby** [comment]
@TJRadarLab 

Does the dataset provide annotation about the target's compensated velocity taking into account ego motion?

**Comment by TJRadarLab** [comment]
> @TJRadarLab
> 
> Does the dataset provide annotation about the target's compensated velocity taking into account ego motion?

Hello, the dataset can provide the raw relative radial velocity as well as the radial velocity compensated after estimating the ego motion using 4D radar point cloud.

**Comment by linqx7** [comment]
> > @TJRadarLab
> > Does the dataset provide annotation about the target's compensated velocity taking into account ego motion?数据集是否提供有关考虑自我运动的目标补偿速度的注释？
> 
> Hello, the dataset can provide the raw relative radial velocity as well as the radial velocity compensated after estimating the ego motion using 4D radar point cloud.您好，该数据集可以提供原始相对径向速度以及使用 4D 雷达点云估计自我运动后补偿的径向速度。

Hollow,请问4D 雷达点云估计自我运动后补偿的径向速度在哪里？
