### ISSUE TITLE
The motion distortion problem of radar point cloud

### ISSUE THREAD

**Issue by Bazinga92445** [TJRadarLab/TJ4DRadSet#20]
Hello,
Thanks for sharing your great work！
I've downloaded all the data and checked the point clouds of all sequences by projecting them on image plane, and I found out there're always some points that just don't make sense. Some are floating in the sky with no corresponding objects, and some are laying on the ground. And I found the same problem from your homepage's visualization video. So I guess there's a motion distortion problem, the mismatched points are from previous frames' landmark, post, cars, etc.
Can you provide raw data as well so developers can try solving this problem on our own?

**Comment by TJRadarLab** [comment]
We only have the Radar PC data and do not have the raw data.
