### ISSUE TITLE
Regarding dataset

### ISSUE THREAD

**Issue by Manishnayak234** [TJRadarLab/TJ4DRadSet#26]
How can i get the dataset? I am Mtech student researching in this domain therefore need this dataset for my research.

**Comment by Guoc0529** [comment]
你们好，看到你们的雷达是OCULII eagle ，我最近也买了一款这个雷达，但是遇见一个问题，雷达在ros下的驱动不能输出点云。请问可以加你们的微信指导一下吗

**Comment by Sawyer-Wu** [comment]
您好，你的邮件我已经收到，我会尽快给您回复，谢谢。

**Comment by Sawyer-Wu** [comment]
您好，你的邮件我已经收到，我会尽快给您回复，谢谢。
