### ISSUE TITLE
About the realease of the LiDAR dara

### ISSUE THREAD

**Issue by StZhang-B** [TJRadarLab/TJ4DRadSet#31]
Hi,

I hope you're doing well. I was wondering if there are any plans to release the LiDAR data for this project. If so, could you kindly provide an estimated timeline for its release?

Thank you for your time and for all the great work!

**Comment by TJRadarLab** [comment]
Email application has been submitted.

**Comment by YangSiri** [comment]
HI, @TJRadarLab 

Where is the entrance of application?
