### ISSUE TITLE
Dataset released structure

### ISSUE THREAD

**Issue by shanflyfly** [TJRadarLab/TJ4DRadSet#5]
hi, thanks for  the mini dataset you released.
can you give some information about the structure about the released dataset?
the data_format.md file is empty.

**Comment by AlexFxf123** [comment]
hello,thanks for the job.
can you provide calib and label information, and camera data of the point cloud?
the txt files only gives data, but no any description.

**Comment by TJRadarLab** [comment]
> hi, thanks for the mini dataset you released. can you give some information about the structure about the released dataset? the data_format.md file is empty.



> hello,thanks for the job. can you provide calib and label information, and camera data of the point cloud? the txt files only gives data, but no any description.

I am very sorry for not replying to your question in time. The label files are organized according to the KITTI format. The 3D bounding boxes are in the camera coordinate system. It should be noted in the calib files that Tr_velo_to_cam is the 4D radar to camera transformation matrix. Tr_imu_to_cam is not used at the moment. You can see the visual script provided for further understanding.

**Comment by TJRadarLab** [comment]
> hello,thanks for the job. can you provide calib and label information, and camera data of the point cloud? the txt files only gives data, but no any description.

We will release the processed images soon.
