### ISSUE TITLE
full dataset release date

### ISSUE THREAD

**Issue by shawrby** [TJRadarLab/TJ4DRadSet#6]
I'm looking forward to it!

When will the full dataset be released?
Please let me know at least roughly.

**Comment by ciwei123** [comment]
@TJRadarLab I am also very much looking forward to the release of the full dataset. Thank you very much!

**Comment by shawrby** [comment]
@ciwei123 

[https://github.com/TJRadarLab/TJ4DRadSet/issues/7](https://github.com/TJRadarLab/TJ4DRadSet/issues/7)
