### ISSUE TITLE
Why haven't you released the full dataset yet?

### ISSUE THREAD

**Issue by shawrby** [TJRadarLab/TJ4DRadSet#7]
@TJRadarLab @yaoshanliang 

It has been almost two months since the TJ4DRadSet paper was published.
And I recently found a research paper using TJ4DRadSet. “3D Object Detection for Multi-Frame 4D Automotive Millimeter-Wave Radar Point Clouds" [https://ieeexplore.ieee.org/abstract/document/9944629](https://ieeexplore.ieee.org/abstract/document/9944629)

Why haven't you released the full dataset yet?
I just don't understand. Come to think of it, I don't understand why an unreleased dataset paper was accepted in the first place.

Any plans to release a full dataset?

**Comment by TJRadarLab** [comment]
Please contact me by email.

**Comment by shawrby** [comment]
@TJRadarLab 

An email was sent to the author of the paper.
Please answer about my question.

**Comment by Stone-sy** [comment]
> Please contact me by email.

I also want the dataset. Could you please tell me your email? Thank you!

**Comment by shawrby** [comment]
@Stone-sy 

It is described in the paper 'TJ4DRadSet: A 4D Radar Dataset for Autonomous Driving'

**Comment by Stone-sy** [comment]
您好！您的邮件我已收到！

**Comment by russellyq** [comment]
@TJRadarLab 

Thanks for your work.

I also want this dataset and your train/val/test split.

How should I get access code of Baidu Disk

**Comment by Sawyer-Wu** [comment]
您好，你的邮件我已经收到，我会尽快给您回复，谢谢。
