### ISSUE TITLE
Will you release the full dataset within this year?

### ISSUE THREAD

**Issue by shawrby** [TJRadarLab/TJ4DRadSet#8]
@TJRadarLab @yaoshanliang 

Will you release the full dataset within this year?

I have received your reply mail.
But I still don't know why it's taking so long to release a dataset.
I think you have published a paper and then you should already have a dataset ready for release.

I would appreciate it if you could know us the exact release schedule.

**Comment by himhan34** [comment]
either will appreciate seeing your team's nice work!
